# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8520c57a48c07925acadaae5eba123c56c3ce7feb662d37babc180b0ccc95b65f18255a46a71c4e62a106a56fc9498f6a8d7654b8f32e92e8e59fa5b08f34029

test:
  secret_key_base: d9f849020f4c76db39516a95309e4bee685acf241a586cc0117eb00de2fa360e98bdff637ed8f809cf831ccd7f8b418ecd6d19f4dcfa85881c5fe40ebe0cb76c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
